---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: botkube-communications
  namespace: default
spec:
  encryptedData:
    comm_config.yaml: AgAPGhMqeK7uqUWj/Ss6rjD31fghopTyKDD8T89XR80k/wU4s/zyOPx4cHYz3E5UK6QFh4gMbzuyVL8rvXOyjo5htqLcuzmiSUjG7LQ+O/6ZiXiPqTBSwf8l0JPTJdtmn90B/5O46yXboEBcowq7jUZJ/eweuPAXYV+1J2YIz9xp2OBTeibSx6Yy8SziOJc+hs6S7jUgf7wUcnafpqT6Mwp7pH/fzXWovT3g/zmA5APTo0N4j2uoPbv3CnnQUCTb1+ufucdQxhqowMjY8fh5esLtNx4sok+92IqUP99t4rElXQklypb21piwoLkBOvREPruBP/PYBgp+6PjLxc7fo3PaAjOZFAWzwC+rUrgaRf73lSQfmLv5BCA1tbFuj6MvsmoGnA33scKRMSh6Pm9Y5SCfyVL3GqNBlolZo6WNSO7nF/2hXPCs/E7FPLBFHfgacwmtYKIV3CglWI/nCBfgFs+kDohmIq0fVMbGEmUsTOKt3L/VDpMsi7FMfK6jRvWEqDOmb/CR/6qMsYIYRuEke5/iQrycm1tgeZhgB2vAIPt9ZdqAdwsh0ExO7COaTo6bjpZ2Kph9e/LtBy+kxofYFao+VyHUq/S4yf4zx07MGZl9w7uPj8GOhHFLfif9wk7CkdHw26a2DiDo+jJ7dqh3qVr2eFYihmMYTGcOeOvZTY7meCx1+3Ikn3I8kGSvfLfxZobmTxkqgXU0Pz9sbiCunPEKVS2TmPan+g8wnUXdm6oJa5gz5QKm5ZFxstCJxg5VKgDzD7wsPtpEWubypstFT3Lu+VBSPlaUVIHHOhKh4kYhmlBXgivHXqk53Bx7TFkLnpD6lP6RhD/6aDI3qirT0jduB3lArIym5SzOpt7FU4Q8lw5GhxJ2YBUa07kWlqHontv0+cXIOzM8KzqvGGBZ/HkTXxZHzZDPCjXUCk3+OrAWjf+16s16mPdnOSdKsJUZsSQMZwjS1rFJnjTsSQ9vW8MsqnnTLNnLGFcxCSbBvW9ZXA7H3Bqka0W13wz5v59GBflBv6ZVNpSBWcn/XGWa3D9c/1fxdb2G1rGLZG+Ta2faa/OFBFiJ05Pvj9Blx1HYifEwUrfL+e1uJjklw6agtg2y3/HGxUxWW4DlBwJnJKTfMQh+wn9/ojETqky6OUNVvfxX/+nYCqDoe8rG5cW63DPvAPjpgkEezDgg1ewWNjmCB2S4w5Acxgrt2jqzQBJCD7yamJfT9xErPwtn5Q1nZPgWmGrv8dWZ
  template:
    metadata:
      name: botkube-communications
      namespace: default
    type: Opaque
