apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: botkube
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.botkube.io/
      chart: botkube
      targetRevision: 1.14.0
      helm:
        valueFiles:
          - $values/helm/botkube/values.yaml
    - repoURL: https://github.com/GauranshMathur/Homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/GauranshMathur/Homelab.git
      targetRevision: main
      path: helm/botkube
      directory:
        include: "botkube-communications-sealed.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: botkube-runtime-config
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
